spring:
  security:
    filter:
      dispatcher-types: ASYNC, FORWARD, INCLUDE, REQUEST
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${CHAT_DB_URL}
    username: ${CHAT_DB_USER}
    password: ${CHAT_DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Hikari
      auto-commit: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  token:
    secret: ${CHAT_JWT_SECRET}
    expiration-time: 1800000
server:
  port: 8080
  error:
    include-stacktrace: never