version: '3'
services:
  server:
    build:
      context: ../server
      dockerfile: docker/Dockerfile_prod
    ports:
      - "8080:8080"
    # should be located in secrets, but its hardcoded here for simplicity
    environment:
      - CHAT_DB_URL=jdbc:postgresql://db:5432/chat
      - CHAT_DB_USER=postgres
      - CHAT_DB_PASS=HgqycDZ4gzG83vrh7fRYXy4wrsJ6X7J8EDB8WnS3gCz5Fhg2zP
      - CHAT_JWT_SECRET=KMBrbAGSM5aR46KgZ3mDJ3mW2nzN2N9qgguU5ESRPrGkg3sEVMQzP6MZ9JE3DTys9JCecgXA7Pqx2m39Jt3enQjGh6Ws44cwCddF
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.1
    ports:
      - "5432:5432"
    # should be located in secrets, but its hardcoded here for simplicity
    environment:
      - POSTGRES_PASSWORD=HgqycDZ4gzG83vrh7fRYXy4wrsJ6X7J8EDB8WnS3gCz5Fhg2zP
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "chat"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  client:
    build:
      context: ../client
      dockerfile: docker/Dockerfile_prod
    ports:
      - "80:80"
    depends_on:
      - server