#STAGE 1
FROM node:18-alpine AS build
WORKDIR /usr/src/app
COPY ../package.json ../package-lock.json ./
RUN npm install
COPY ../ .
RUN npm run build:dev

#STAGE 2
FROM nginx:1.17.1-alpine
COPY ../nginx/* /etc/nginx/
COPY --from=build /usr/src/app/dist/chat /usr/share/nginx/html